# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Will Summerhill
#email: 
description: >- # this means to ignore newlines until "baseurl:"
  Red Teaming & Pentesting

baseurl: "" # the subpath of your site, e.g. /blog
domain: wsummerhill.github.io # enforce HTTPS
url: "https://wsummerhill.github.io" # the base hostname & protocol for your site
repository: "wsummerhill/wsummerhill.github.io"
logo: logo.png

twitter_username: bsummerz
github_username:  wsummerhill


# Build settings
markdown: kramdown

# Theme - remote
#remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

lang: en-US

search: true
search_full_content: false 

# Subpages for website (about.md, 404.md, etc)
include:
  - _pages

# Paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/


# Left side bar - Site Author
author:
  name             : "Will Summerhill"
  avatar           : 
  bio              : "I am a _**wonderful**_ person."
  location         : "Canada"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bsummerz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wsummerhill"


# Site Footer - DOESNT LOAD YET
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/bsummerz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wsummerhill"

# Footer - Copyright
copyright: "© 2022 Will Summerhill."


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - Gemfile
   - Gemfile.lock
